version: '3'
services:
  db:
    image: postgres:9.6
    env_file: .env.production
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    build: .
    env_file: .env.production
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - public:/app/public
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
      args:
        GEOLOCATION_API_KEY: "${GEOLOCATION_API_KEY}"
        IMPORT_TRIGGER_URL: "${IMPORT_TRIGGER_URL}"
        GEOLOCATION_DATABASE_URL: "${GEOLOCATION_DATABASE_URL}"
    depends_on:
    - db
    volumes:
    - solrdata:/opt/solr/server/solr
    restart: unless-stopped
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
      - 443:443
    volumes:
      - public:/app/public
volumes:
  pgdata:
  solrdata:
  public:
