version: '3'
services:
  db:
    image: postgres:9.6
    env_file: .env.staging
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped
  app:
    build: .
    env_file: .env.staging
    command: bundle exec puma -C config/puma.rb
    depends_on:
      - db
    restart: unless-stopped
    volumes:
      - app:/app
      - webdata:/app/public/uploads
  solr:
    build:
      context: ./solr
      dockerfile: Dockerfile
      args:
        GEOLOCATION_API_KEY: "${GEOLOCATION_API_KEY}"
        IMPORT_TRIGGER_URL: "${IMPORT_TRIGGER_URL}"
        GEOLOCATION_DATABASE_URL: "${GEOLOCATION_DATABASE_URL}"
    depends_on:
    - db
    volumes:
    - solrdata:/opt/solr/server/solr
    restart: unless-stopped
  web:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
    volumes:
      - app:/app
volumes:
  pgdata:
  solrdata:
  webdata:
  app:
